server:
  port: 8080
mpesa:
  daraja:
    consumer-key: qIJwWMjoeIdtetQCX9HLZLiFGupRbvoK
    consumer-secret: 7UYaI2TFTaregJmA
    grant-type: client_credentials
    oauth-endpoint: https://sandbox.safaricom.co.ke/oauth/v1/generate
    